{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "todo-chatbot.labels" . | nindent 4 }}
    app: postgres
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres
  selector:
    {{- include "todo-chatbot.selectorLabels" . | nindent 4 }}
    app: postgres
{{- end }}
