"""
Generic Problem Details (RFC 7807 style) error response schema.

PURPOSE:
- Define a consistent JSON error format for all REST APIs.
- Align with RFC 7807 "Problem Details for HTTP APIs" while allowing extensions.
- Be framework- and language-agnostic.

CONTENT-TYPE:
- Use: Content-Type: application/problem+json

BASE FIELDS (problem details object):
- type:    string (URI identifying the problem type; SHOULD be stable)
- title:   string (short, human-readable summary of the problem type)
- status:  integer (HTTP status code generated by the origin server)
- detail:  string (human-readable explanation specific to this occurrence)
- instance:string (URI reference that identifies the specific occurrence
                  of the problem, e.g. the request path)

OPTIONAL FIELDS:
- errors:  array of field-level validation errors, for 400/422 cases:
           [
             { "field": "title", "message": "Title is required." },
             { "field": "due_date", "message": "Must be in the future." }
           ]
- Any other extension members are allowed per RFC 7807.

EXAMPLE (422 validation error):

{
  "type": "https://example.com/errors/validation-error",
  "title": "Validation failed",
  "status": 422,
  "detail": "One or more fields are invalid.",
  "instance": "/api/v1/tasks",
  "errors": [
    { "field": "title", "message": "Title is required." }
  ]
}

EXAMPLE (404 not found):

{
  "type": "https://example.com/errors/resource-not-found",
  "title": "Resource not found",
  "status": 404,
  "detail": "Task with id 123 was not found.",
  "instance": "/api/v1/tasks/123"
}

USAGE:
- Every REST API should:
  - Return 4xx/5xx errors in this format.
  - Set Content-Type: application/problem+json on error responses.
  - Prefer stable "type" URIs per problem category (validation-error,
    not-found, conflict, unauthorized, forbidden, etc.).
- Framework-specific Skills (FastAPI, Express, etc.) should implement
  central error handlers/middleware that always emit this shape.
"""
