"""
Standard Alembic env.py for Neon Postgres with SQLModel metadata.

PURPOSE:
- Load the Neon DATABASE_URL from environment variables.
- Use the same engine URL as the application (via app.db).
- Expose SQLModel metadata as Alembic's target_metadata so that
  migrations can be autogenerated from models.

HOW TO USE:
- Use this file as a reference when creating `alembic/env.py`.
- Adjust import paths (app.db, metadata) to match your project.
"""

```typescript

from __future__ import annotations

import os
from logging.config import fileConfig

from sqlalchemy import engine_from_config, pool
from alembic import context

# Import the app's DB config and metadata
from app.db import NEON_DATABASE_URL_ENV, metadata  # adjust module path

# this is the Alembic Config object, which provides access to
# the values within the .ini file in use.
config = context.config

# Interpret the config file for Python logging.
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# Set the SQLAlchemy url from the same env var the app uses.
database_url = os.getenv(NEON_DATABASE_URL_ENV)
if not database_url:
    raise RuntimeError(f"{NEON_DATABASE_URL_ENV} environment variable is not set")

config.set_main_option("sqlalchemy.url", database_url)

# Set target_metadata for 'autogenerate' support.
target_metadata = metadata


def run_migrations_offline() -> None:
    """
    Run migrations in 'offline' mode.

    This configures the context with just a URL and not an Engine.
    Calls to context.execute() emit the given string to the script output.
    """
    url = config.get_main_option("sqlalchemy.url")
    if not url:
        raise RuntimeError("sqlalchemy.url is not configured")

    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        compare_type=True,
    )

    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """
    Run migrations in 'online' mode.

    In this scenario, we need to create an Engine and associate a
    connection with the context.
    """
    connectable = engine_from_config(
        config.get_section(config.config_ini_section) or {},
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            compare_type=True,
        )

        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
```